const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   //     STORE_QUEUED_CARDS: "STORE_QUEUED_CARDS",
   //     UPDATE_INDEX_OF_CURRENT_CARD: "UPDATE_INDEX_OF_CURRENT_CARDS",
   STORE_LIPSTICK: "STORE_LIPSTICK",
   UPDATE_CURRENT_USER_TAGS: "UPDATE_CURRENT_USER_TAGS",
   UPDATE_ALL_CURRENT_USER_TAGS: "UPDATE_ALL_CURRENT_USER_TAGS",

   //UPDATE_INDEX_LIPSTICK_MATCHES: "UPDATE_INDEX_OF_LIPSTICK"
};

export default actions;
